// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *settings → nav menu*
 */
export interface SettingsDocumentDataNavMenuItem {
  /**
   * link field in *settings → nav menu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.nav_menu[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * link text field in *settings → nav menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.nav_menu[].link_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_text: prismic.KeyTextField;
}

/**
 * Item in *settings → company link*
 */
export interface SettingsDocumentDataCompanyLinkItem {
  /**
   * link field in *settings → company link*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.company_link[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * label field in *settings → company link*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.company_link[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Item in *settings → product link*
 */
export interface SettingsDocumentDataProductLinkItem {
  /**
   * link field in *settings → product link*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.product_link[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * label field in *settings → product link*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.product_link[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Item in *settings → resources link*
 */
export interface SettingsDocumentDataResourcesLinkItem {
  /**
   * link field in *settings → resources link*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.resources_link[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * label field in *settings → resources link*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.resources_link[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Item in *settings → legal link*
 */
export interface SettingsDocumentDataLegalLinkItem {
  /**
   * link field in *settings → legal link*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.legal_link[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * label field in *settings → legal link*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.legal_link[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Item in *settings → footer logo*
 */
export interface SettingsDocumentDataFooterLogoItem {
  /**
   * logo field in *settings → footer logo*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_logo[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * link field in *settings → footer logo*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_logo[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for settings documents
 */
interface SettingsDocumentData {
  /**
   * nav menu field in *settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.nav_menu[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  nav_menu: prismic.GroupField<Simplify<SettingsDocumentDataNavMenuItem>>;

  /**
   * FnKnow logo field in *settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.fnknow_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  fnknow_logo: prismic.ImageField<never>;

  /**
   * homepage banner field in *settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.homepage_banner
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  homepage_banner: prismic.ImageField<never>;

  /**
   * company link field in *settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.company_link[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  company_link: prismic.GroupField<
    Simplify<SettingsDocumentDataCompanyLinkItem>
  >;

  /**
   * product link field in *settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.product_link[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  product_link: prismic.GroupField<
    Simplify<SettingsDocumentDataProductLinkItem>
  >;

  /**
   * resources link field in *settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.resources_link[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  resources_link: prismic.GroupField<
    Simplify<SettingsDocumentDataResourcesLinkItem>
  >;

  /**
   * legal link field in *settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.legal_link[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  legal_link: prismic.GroupField<Simplify<SettingsDocumentDataLegalLinkItem>>;

  /**
   * footer logo field in *settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_logo[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  footer_logo: prismic.GroupField<Simplify<SettingsDocumentDataFooterLogoItem>>;

  /**
   * copyright field in *settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.copyright
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  copyright: prismic.KeyTextField;
}

/**
 * settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes = SettingsDocument;

/**
 * Primary content in *FooterLogo → Primary*
 */
export interface FooterLogoSliceDefaultPrimary {
  /**
   * logo field in *FooterLogo → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_logo.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Default variation for FooterLogo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterLogoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FooterLogoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FooterLogo*
 */
type FooterLogoSliceVariation = FooterLogoSliceDefault;

/**
 * FooterLogo Shared Slice
 *
 * - **API ID**: `footer_logo`
 * - **Description**: FooterLogo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterLogoSlice = prismic.SharedSlice<
  "footer_logo",
  FooterLogoSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavMenuItem,
      SettingsDocumentDataCompanyLinkItem,
      SettingsDocumentDataProductLinkItem,
      SettingsDocumentDataResourcesLinkItem,
      SettingsDocumentDataLegalLinkItem,
      SettingsDocumentDataFooterLogoItem,
      AllDocumentTypes,
      FooterLogoSlice,
      FooterLogoSliceDefaultPrimary,
      FooterLogoSliceVariation,
      FooterLogoSliceDefault,
    };
  }
}
