// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_section: dynamic(() => import("./AboutSection")),
  banner: dynamic(() => import("./Banner")),
  financial_learning: dynamic(() => import("./FinancialLearning")),
  team: dynamic(() => import("./Team")),
  user_review: dynamic(() => import("./UserReview")),
};
