import Footer from "@/components/footer/Footer";
import Header from "@/components/header/Header";
import clsx from "clsx";
import type { Metadata } from "next";
import { Glory } from "next/font/google";
import "./globals.css";

const glory = Glory({
    subsets: ["latin"],
    variable: "--font-glory",
    display: "swap",
});

export const metadata: Metadata = {
    title: "Home",
    // description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className={clsx(glory.variable)}>
            <body>
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
